SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[QuizType](
	[QuizTypeID] [char](3) NOT NULL,
	[QuizTypeName] [varchar](30) NOT NULL,
 CONSTRAINT [PK__QuizType__559C8BE32FE051CE] PRIMARY KEY CLUSTERED 
(
	[QuizTypeID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

