CREATE TABLE QuizResults
(
  ResultID INTEGER(6) NOT NULL,
  QuizID INTEGER(6) NOT NULL,
  UserID INTEGER(6) NOT NULL,
  Score INTEGER(3) NOT NULL,
  CorrectAnswers INTEGER(3) NOT NULL,
  TotalQuestions INTEGER(3) NOT NULL,
  TakenAt DATE NOT NULL,
  PRIMARY KEY (ResultID),
  FOREIGN KEY (QuizID) REFERENCES Quiz(QuizID),
  FOREIGN KEY (UserID) REFERENCES User(UserID)
);
