SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[QuizResults](
	[ResultID] [int] IDENTITY(1,1) NOT NULL,
	[QuizID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
	[Score] [int] NOT NULL,
	[CorrectAnswers] [int] NOT NULL,
	[TotalQuestions] [int] NOT NULL,
	[TakenAt] [date] NOT NULL,
 CONSTRAINT [PK__QuizResu__9769022830C1ADF9] PRIMARY KEY CLUSTERED 
(
	[ResultID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[QuizResults]  WITH CHECK ADD  CONSTRAINT [FK__QuizResul__QuizI__4B7734FF] FOREIGN KEY([QuizID])
REFERENCES [dbo].[Quiz] ([QuizID])
GO

ALTER TABLE [dbo].[QuizResults] CHECK CONSTRAINT [FK__QuizResul__QuizI__4B7734FF]
GO

ALTER TABLE [dbo].[QuizResults]  WITH CHECK ADD  CONSTRAINT [FK__QuizResul__UserI__4C6B5938] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO

ALTER TABLE [dbo].[QuizResults] CHECK CONSTRAINT [FK__QuizResul__UserI__4C6B5938]
GO

